### ISSUE TITLE
Rotating LogFiles cause Http Status 416 Errors

### ISSUE THREAD

**Issue by meniku** [sentric/hannibal#13]
When a HBase LogFile gets rotated, following attempts to collect new portions of the logfile cause Http Status 416 Errors:

```
[ERROR] [02/07/2013 00:00:49.464] [application-akka.actor.default-dispatcher-3] [akka://application/user/updateMetricsActor] couldn't load Compaction Metrics from URL: 'http://c1-s5.cluster:60030/logs/hbase-hbase-regionserver-c1-s5.log (statusCode was: 416) 
```

Wikipedia describes Http Status Errors 416 as:

```
416 Requested Range Not Satisfiable
The client has asked for a portion of the file, but the server cannot supply that portion.[2] For example, if the client asked for a part of the file that lies beyond the end of the file.[2]
```

We could add a check for code 416 to the `LogFile` class, reset the logOffsets and then try again to fetch the logfile. Would that work?

**Comment by alexandre-normand** [comment]
Yes, that would work. I initially was handling the 416 (since that's in the spec) but, after testing with specific range values that I knew were larger than the file size and getting a 200 with a `*` range value in the headers, I had settled on this:

```
if (rangeValue eq "*") {
      // The offset doesn't match the file content because, presumably, of log file rotation,
      // reset the offset to 0
```

I don't know if that's because of different versions but it's safer to just handle both cases (as is, 416 and the range value returned in the response being `*`.

**Comment by meniku** [comment]
fix is now in the 'master'-branch
